bash scripting for s3

diff --git a/s3/bash-scripts/create-bucket b/s3/bash-scripts/create-bucket
--- a/s3/bash-scripts/create-bucket
+++ b/s3/bash-scripts/create-bucket
@@ -1,16 +1,21 @@
 #! /usr/bin/env bash
 echo "== create bucket"
 
-# Check if 1 argument is provided
+# Exit immediately if any command returns a non-zero status
+set -e
+
+# Check for bucket name
 if [ -z "$1" ]; then
     echo "No bucket name provided."
     echo "./create-bucket <bucket-name>"
     exit 1
 fi
 
+BUCKET_NAME=$1
+
 # https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
 aws s3api create-bucket \
---bucket $1 \
+--bucket $BUCKET_NAME  \
 --create-bucket-configuration "LocationConstraint=eu-west-1" \
 --query Location \
 --output text
diff --git a/s3/bash-scripts/delete-bucket b/s3/bash-scripts/delete-bucket
--- a/s3/bash-scripts/delete-bucket
+++ b/s3/bash-scripts/delete-bucket
@@ -1,13 +1,18 @@
 #! /usr/bin/env bash
 echo "== delete bucket"
 
-# Check if 1 argument is provided
+# Exit immediately if any command returns a non-zero status
+set -e
+
+# Check for bucket name
 if [ -z "$1" ]; then
     echo "No bucket name provided."
     echo "./delete-bucket <bucket-name>"
     exit 1
 fi
 
+BUCKET_NAME=$1
+
 # https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
 aws s3api delete-bucket \
---bucket $1 \
+--bucket $BUCKET_NAME \
diff --git a/s3/bash-scripts/list-objects b/s3/bash-scripts/list-objects
--- a/s3/bash-scripts/list-objects
+++ b/s3/bash-scripts/list-objects
@@ -1,2 +1,28 @@
 #! /usr/bin/env bash
 echo "== list objects"
+
+# Exit immediately if any command returns a non-zero status
+set -e
+
+# Check for bucket name
+if [ -z "$1" ]; then
+    echo "Usage:"
+    echo "./list-objects <bucket-name>"
+    exit 1
+fi 
+
+BUCKET_NAME=$1
+
+# Get the list of all objects in the bucket
+# https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects-v2.html
+OBJECTS=$(aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --query 'Contents[].{Key: Key}' --output json)
+
+# Check if the bucket is empty
+if [ "$OBJECTS" == "null" ] || [ "$OBJECTS" == "[]" ]; then
+    echo "No objects in bucket $BUCKET_NAME."
+    exit 0
+fi
+
+# Parse the JSON and list the objects
+echo "Objects in bucket $BUCKET_NAME:"
+echo "$OBJECTS" | jq -r '.[]'
diff --git a/s3/bash-scripts/sync b/s3/bash-scripts/sync
--- a/s3/bash-scripts/sync
+++ b/s3/bash-scripts/sync
@@ -1,2 +1,39 @@
 #! /usr/bin/env bash
 echo "== sync"
+
+# Exit immediately if any command returns a non-zero status
+set -e
+
+# Check for bucket name
+if [ -z "$1" ] || [ -z "$2" ]; then
+    echo "Usage:"
+    echo "./sync <bucket-name> <filename-prefix>"
+    exit 1
+fi 
+
+BUCKET_NAME=$1
+FILENAME_PREFIX=$2
+
+# location to store files
+OUTPUT_DIR="/tmp/s3-bash-scripts"
+
+# remove the folder if it already exits
+rm -r $OUTPUT_DIR
+
+# create output folder
+mkdir -p $OUTPUT_DIR
+
+# random number to determine the number of files to create
+NUM_FILES=$((RANDOM % 6 + 5))
+
+for ((i=1; i<=$NUM_FILES; i++)) do 
+    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
+
+    # generate random data and write it to the file
+    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024+ 1)) 2>/dev/null
+done
+
+tree $OUTPUT_DIR
+
+# https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html
+aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
